<?php

namespace FondOfSpryker\Zed\SizeSwitcher\Business\Publisher;

use Codeception\Test\Unit;
use FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToEventBehaviorFacadeBridge;
use FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToProductPageSearchFacadeBridge;
use FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToStoreFacadeBridge;
use FondOfSpryker\Zed\SizeSwitcher\Persistence\SizeSwitcherRepository;

class ProductAbstractPageSearchPublisherTest extends Unit
{
    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Business\Publisher\ProductAbstractPageSearchPublisher
     */
    protected $publisher;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToEventBehaviorFacadeBridge|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $storeFacadeMock;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToEventBehaviorFacadeBridge|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $eventFacadeMock;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToProductPageSearchFacadeBridge|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productPageSearchFacadeMock;

    /**
     * @var \Generated\Shared\Transfer\EventEntityTransfer[]
     */
    protected $eventTransferCollection;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Persistence\SizeSwitcherRepository|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $repositoryMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->storeFacadeMock = $this->getMockBuilder(SizeSwitcherToStoreFacadeBridge::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->eventFacadeMock = $this->getMockBuilder(SizeSwitcherToEventBehaviorFacadeBridge::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->productPageSearchFacadeMock = $this->getMockBuilder(SizeSwitcherToProductPageSearchFacadeBridge::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->repositoryMock = $this->getMockBuilder(SizeSwitcherRepository::class)
            ->disableOriginalConstructor()
            ->setMethods()
            ->getMock();

        $eventEntityTransfer = include codecept_data_dir('EventEntityTransfer.php');
        $this->eventTransferCollection = [
            $eventEntityTransfer,
        ];

        $this->publisher = new ProductAbstractPageSearchPublisher(
            $this->storeFacadeMock,
            $this->eventFacadeMock,
            $this->productPageSearchFacadeMock,
            $this->repositoryMock
        );
    }

    /**
     * @return void
     */
    public function testPublish(): void
    {
        $this->eventFacadeMock->expects($this->once())
            ->method('getEventTransferIds');

        $this->publisher->publish($this->eventTransferCollection);
    }
}
