<?php

namespace FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade;

use Codeception\Test\Unit;
use Spryker\Zed\ProductPageSearch\Business\ProductPageSearchFacade;

class SizeSwitcherToProductPageSearchFacadeBridgeTest extends Unit
{
    /**
     * @var \Spryker\Zed\ProductPageSearch\Business\ProductPageSearchFacade|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productPageSearchFacadeMock;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToStoreFacadeBridge|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $storeFacadeMock;

    /**
     * @var
     */
    protected $repositoryMock;

    /**
     * @return void
     */
    protected function _before(): void
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->productPageSearchFacadeMock = $this->getMockBuilder(ProductPageSearchFacade::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->bridge = new SizeSwitcherToProductPageSearchFacadeBridge($this->productPageSearchFacadeMock);
    }

    /**
     * @return void
     */
    public function testPublish(): void
    {
        $this->productPageSearchFacadeMock->expects($this->once())
            ->method('publish')
            ->with([1612, 1613, 1614]);

        $this->bridge->publish([1612, 1613, 1614]);
    }

    /**
     * @return void
     */
    public function testRefresh(): void
    {
        $this->productPageSearchFacadeMock->expects($this->once())
            ->method('refresh')
            ->with([1612, 1613, 1614], []);

        $this->bridge->refresh([1612, 1613, 1614], []);
    }
}
