<?php

namespace FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade;

use Codeception\Test\Unit;
use Spryker\Zed\EventBehavior\Business\EventBehaviorFacade;

class SizeSwitcherToEventBehaviorFacadeBridgeTest extends Unit
{
    /**
     * @var \Spryker\Zed\EventBehavior\Business\EventBehaviorFacade|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $eventBehaviorFacadeMock;

    /**
     * @var SizeSwitcherToEventBehaviorFacadeBridge
     */
    protected $bridge;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->eventBehaviorFacadeMock = $this->getMockBuilder(EventBehaviorFacade::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->bridge = new SizeSwitcherToEventBehaviorFacadeBridge($this->eventBehaviorFacadeMock);
    }

    /**
     * @return void
     */
    public function testGetEventTransferIds(): void
    {
        $eventEntityTransfer = include codecept_data_dir('EventEntityTransfer.php');
        $eventEntityTransferCollection = [
            $eventEntityTransfer,
        ];

        $this->eventBehaviorFacadeMock->expects($this->once())
            ->method('getEventTransferIds')
            ->with($eventEntityTransferCollection)
            ->willReturn([1612]);

        $ids = $this->bridge->getEventTransferIds($eventEntityTransferCollection);
        $this->assertIsArray($ids);
    }
}
