<?php

namespace FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade;

use Codeception\Test\Unit;
use Generated\Shared\Transfer\StoreTransfer;
use Spryker\Zed\Store\Business\StoreFacade;

class SizeSwitcherToStoreFacadeBridgeTest extends Unit
{
    /**
     * @var \Spryker\Zed\Store\Business\StoreFacade|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $storeFacadeMock;

    /**
     * @var \FondOfSpryker\Zed\SizeSwitcher\Dependency\Facade\SizeSwitcherToStoreFacadeBridge
     */
    protected $bridge;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->storeFacadeMock = $this->getMockBuilder(StoreFacade::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->bridge = new SizeSwitcherToStoreFacadeBridge($this->storeFacadeMock);
    }

    /**
     * @return void
     */
    public function testGetCurrentStore(): void
    {
        $storeTransfer = new StoreTransfer();
        $storeTransfer->setIdStore(1);
        $storeTransfer->setName('TEST_STORE');

        $this->storeFacadeMock->expects($this->once())
            ->method('getCurrentStore')
            ->willReturn($storeTransfer);

        $result = $this->bridge->getCurrentStore();

        $this->assertInstanceOf(StoreTransfer::class, $result);
    }
}
